// <auto-generated />
using Cooprol.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cooprol.Data.Migrations
{
    [DbContext(typeof(CooprolContext))]
    [Migration("20230918163155_initialize")]
    partial class initialize
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_0900_ai_ci")
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");

            modelBuilder.Entity("Cooprol.Data.Models.Bill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("DateB")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("dateB");

                    b.Property<int>("Deductions")
                        .HasColumnType("int")
                        .HasColumnName("deductions");

                    b.Property<int>("IdProducer")
                        .HasColumnType("int")
                        .HasColumnName("idProducer");

                    b.Property<int>("LProduced")
                        .HasColumnType("int")
                        .HasColumnName("lProduced");

                    b.Property<int>("ToPay")
                        .HasColumnType("int")
                        .HasColumnName("toPay");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdProducer" }, "idProducer");

                    b.ToTable("Bill", (string)null);
                });

            modelBuilder.Entity("Cooprol.Data.Models.Producer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CellNumber")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("cellNumber");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("isActive");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<string>("NumberCc")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("numberCc");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("Producer", (string)null);
                });

            modelBuilder.Entity("Cooprol.Data.Models.Bill", b =>
                {
                    b.HasOne("Cooprol.Data.Models.Producer", "IdProducerNavigation")
                        .WithMany("Bills")
                        .HasForeignKey("IdProducer")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("Bill_ibfk_1");

                    b.Navigation("IdProducerNavigation");
                });

            modelBuilder.Entity("Cooprol.Data.Models.Producer", b =>
                {
                    b.Navigation("Bills");
                });
#pragma warning restore 612, 618
        }
    }
}
